eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: demo-subject
words: I,You,He,She,It

---
spring:
  profiles: demo-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: demo-article
words: a,the

---
spring:
  profiles: demo-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: demo-noun
words: boat,book,vote,seat,backpack,partition,groundhog